log system startup errors
git-svn-id: http://svn.code.sf.net/p/rts-2/code/trunk/rts-2@9896 65ab8f4e-f147-0410-b3a9-f14133ecfe55

diff --git a/rts2.initd b/rts2.initd
--- a/rts2.initd
+++ b/rts2.initd
@@ -84,7 +84,7 @@ case $system in
 					sleep 1
 				done
 			fi
-			log_end_msg $2
+			rts2_log_end_msg $2 $3
 		}
 		function daemon
 		{
@@ -102,6 +102,24 @@ DEVICE_CONFIG=/etc/rts2/devices
 SERVICE_CONFIG=/etc/rts2/services
 RTS2_BIN_PREFIX=/usr/local/bin
 RTS2_PID_PREFIX=/var/run/rts2_
+RTS2_LOG=/var/log/rts2-debug
+
+function rts2_log_daemon_msg
+{
+	log_daemon_msg $*
+	echo `date +'%Y-%M-%DT%H:%M:%S %Z'` '===<<<<<' $* >>$RTS2_LOG
+}
+
+function rts2_log_end_msg
+{
+	log_end_msg $1
+	if [ $1 == 0 ]; then
+		echo `date +'%Y-%M-%DT%H:%M:%S %Z'` '===>>> ok' $2 >>$RTS2_LOG
+	else
+		echo `date +'%Y-%M-%DT%H:%M:%S %Z'` '===>>> failed' $2 >>$RTS2_LOG
+	fi
+}
+
 
 function rts2-start
 {
@@ -111,14 +129,14 @@ function rts2-start
 		fi
 		case $system in
 			debian)
-				log_daemon_msg "Starting RTS2 centrald daemon on port $centrald_port" "rts2-centrald"
-				start-stop-daemon --start --pidfile ${RTS2_PID_PREFIX}centrald_${centrald_port} --exec $RTS2_BIN_PREFIX/rts2-centrald -- --local-port $centrald_port $centrald_options
-				log_end_msg $?
+				rts2_log_daemon_msg "Starting RTS2 centrald daemon on port $centrald_port" "rts2-centrald"
+				start-stop-daemon --start --pidfile ${RTS2_PID_PREFIX}centrald_${centrald_port} --exec $RTS2_BIN_PREFIX/rts2-centrald -- --local-port $centrald_port $centrald_options >>$RTS2_LOG 2>&1
+				rts2_log_end_msg $? "rts2-centrald $centrald_options"
 				;;
 			redhat|slackware|cygwin)
-				log_daemon_msg "Starting RTS2 centrald daemon on port $centrald_port" "rts2-centrald"
-				daemon $RTS2_BIN_PREFIX/rts2-centrald $centrald_options
-				log_end_msg $?
+				rts2_log_daemon_msg "Starting RTS2 centrald daemon on port $centrald_port" "rts2-centrald"
+				daemon $RTS2_BIN_PREFIX/rts2-centrald $centrald_options >>$RTS2_LOG 2>&1
+				rts2_log_end_msg $? "rts2-centrald $centrald_options"
 				;;
 		esac
 	done
@@ -126,28 +144,28 @@ function rts2-start
 	cat $DEVICE_CONFIG | sed -e 's/#.*$//' | egrep -v '^\s*$' | while read device type device_name options; do
 		case $system in
 			debian)
-				log_daemon_msg "Starting $device_name" "rts2-$device-$type"
-				start-stop-daemon --start --pidfile ${RTS2_PID_PREFIX}${device_name} --exec $RTS2_BIN_PREFIX/rts2-$device-$type -- $options $CENTRALD_OPTIONS -d $device_name
-				log_end_msg $?
+				rts2_log_daemon_msg "Starting $device_name" "rts2-$device-$type"
+				start-stop-daemon --start --pidfile ${RTS2_PID_PREFIX}${device_name} --exec $RTS2_BIN_PREFIX/rts2-$device-$type -- $options $CENTRALD_OPTIONS -d $device_name >>$RTS2_LOG 2>&1 
+				rts2_log_end_msg $? $device_name
 				;;
 			redhat|slackware|cygwin)
-				log_daemon_msg "Starting $device_name rts2-$device-$type"
-				daemon $RTS2_BIN_PREFIX/rts2-$device-$type $options $CENTRALD_OPTIONS -d $device_name
-				wait_pid ${RTS2_PID_PREFIX}${device_name} $?
+				rts2_log_daemon_msg "Starting $device_name rts2-$device-$type"
+				daemon $RTS2_BIN_PREFIX/rts2-$device-$type $options $CENTRALD_OPTIONS -d $device_name >>$RTS2_LOG 2>&1
+				wait_pid ${RTS2_PID_PREFIX}${device_name} $? $device_name
 				;;
 		esac
 	done
 	cat $SERVICE_CONFIG | sed -e 's/#.*$//' | egrep -v '^\s*$' | while read service service_name options; do
 		case $system in
 			debian)
-				log_daemon_msg "Starting $service_name" "rts2-$service"
-				start-stop-daemon --start --pidfile ${RTS2_PID_PREFIX}${service_name} --exec $RTS2_BIN_PREFIX/rts2-$service -- $options $CENTRALD_OPTIONS -d $service_name
-				log_end_msg $?
+				rts2_log_daemon_msg "Starting $service_name" "rts2-$service"
+				start-stop-daemon --start --pidfile ${RTS2_PID_PREFIX}${service_name} --exec $RTS2_BIN_PREFIX/rts2-$service -- $options $CENTRALD_OPTIONS -d $service_name >>$RTS2_LOG 2>&1
+				rts2_log_end_msg $? $service_name
 				;;
 			redhat|slackware|cygwin)
-				log_daemon_msg "Starting $service_name rts2-$service"
-				daemon $RTS2_BIN_PREFIX/rts2-$service $options $CENTRALD_OPTIONS -d $service_name
-				wait_pid ${RTS2_PID_PREFIX}${service_name} $?
+				rts2_log_daemon_msg "Starting $service_name rts2-$service"
+				daemon $RTS2_BIN_PREFIX/rts2-$service $options $CENTRALD_OPTIONS -d $service_name >>$RTS2_LOG 2>&1
+				wait_pid ${RTS2_PID_PREFIX}${service_name} $? $service_name
 				;;
 		esac
 	done
@@ -159,16 +177,16 @@ function rts2-stop-devices
 		case $system in
 			debian)
 				if [ -e ${RTS2_PID_PREFIX}${device_name} ]; then
-					log_daemon_msg "Stopping $device_name" "rts2-$device-$type"
-					start-stop-daemon --stop --pidfile ${RTS2_PID_PREFIX}${device_name}
-					log_end_msg $?
+					rts2_log_daemon_msg "Stopping $device_name" "rts2-$device-$type"
+					start-stop-daemon --stop --pidfile ${RTS2_PID_PREFIX}${device_name} >>$RTS2_LOG 2>&1
+					rts2_log_end_msg $? $device_name
 				fi
 				;;
 			redhat|slackware|cygwin)
 				if [ -e ${RTS2_PID_PREFIX}${device_name} ]; then
-					log_daemon_msg "Stopping $device_name" "rts2-$device-$type"
-					killproc `head -n 1 ${RTS2_PID_PREFIX}${device_name}`
-					log_end_msg $?
+					rts2_log_daemon_msg "Stopping $device_name" "rts2-$device-$type"
+					killproc `head -n 1 ${RTS2_PID_PREFIX}${device_name}` >>$RTS2_LOG 2>&1
+					rts2_log_end_msg $? $device_name
 					rm -f ${RTS2_PID_PREFIX}${device_name}
 				fi
 				;;
@@ -182,16 +200,16 @@ function rts2-stop-services
 		case $system in
 			debian)
 				if [ -e ${RTS2_PID_PREFIX}$service_name ]; then
-					log_daemon_msg "Stopping $service_name" "$service_name"
-					start-stop-daemon --stop --pidfile ${RTS2_PID_PREFIX}${service_name}
-					log_end_msg $?
+					rts2_log_daemon_msg "Stopping $service_name" "$service_name"
+					start-stop-daemon --stop --pidfile ${RTS2_PID_PREFIX}${service_name} >>$RTS2_LOG 2>&1
+					rts2_log_end_msg $? $service_name
 				fi
 				;;
 			redhat|slackware|cygwin)
 				if [ -s ${RTS2_PID_PREFIX}$service_name ]; then
-					log_daemon_msg "Stopping $service_name" "$service_name"
-					killproc `head -n 1 ${RTS2_PID_PREFIX}$service_name`
-					log_end_msg $?
+					rts2_log_daemon_msg "Stopping $service_name" "$service_name"
+					killproc `head -n 1 ${RTS2_PID_PREFIX}$service_name` >>$RTS2_LOG 2>&1
+					rts2_log_end_msg $? $service_name
 					rm -f ${RTS2_PID_PREFIX}$service_name
 				fi
 				;;
@@ -207,15 +225,15 @@ function rts2-stop
 		for cf in ${RTS2_PID_PREFIX}centrald_*; do
 		  	case $system in
 				debian)
-					log_daemon_msg "Stopping centrald daemon" "rts2-centrald"
-					start-stop-daemon --stop --pidfile $cf
-					log_end_msg $?
+					rts2_log_daemon_msg "Stopping centrald daemon" "rts2-centrald"
+					start-stop-daemon --stop --pidfile $cf >>$RTS2_LOG 2>&1
+					rts2_log_end_msg $? rts2-centrald
 					;;
 				redhat|slackware|cygwin)
 					if [ -s $cf ]; then
-						log_daemon_msg "Stopping centrald daemon" "rts2-centrald"
-						killproc `head -n 1 $cf`
-						log_end_msg $?
+						rts2_log_daemon_msg "Stopping centrald daemon" "rts2-centrald"
+						killproc `head -n 1 $cf` >>$RTS2_LOG 2>&1
+						rts2_log_end_msg $? rts2-centrald
 						rm -f $cf
 					fi
 					;;
@@ -231,9 +249,9 @@ function rts2-reload
 			pid=`cat $cf`
 			case $system in
 				debian|redhat|slackware|cygwin)
-					log_daemon_msg "Reloading centrald daemon (PID $cf)" "rts2-centrald"
-				  	kill -1 `cat $cf`
-					log_end_msg $?
+					rts2_log_daemon_msg "Reloading centrald daemon (PID $cf)" "rts2-centrald"
+				  	kill -1 `cat $cf` >>$RTS2_LOG 2>&1
+					rts2_log_end_msg $? rts2-centrald
 					;;
 			esac
 		done
@@ -242,9 +260,9 @@ function rts2-reload
 		if [ -f ${RTS2_PID_PREFIX}${device_name} ]; then
 		  	case $system in
 				debian|redhat|slackware|cygwin)
-					log_daemon_msg "Reloading $device_name" "rts2-$device-$type"
-					kill -1 `cat ${RTS2_PID_PREFIX}${device_name}`
-					log_end_msg $?
+					rts2_log_daemon_msg "Reloading $device_name" "rts2-$device-$type"
+					kill -1 `cat ${RTS2_PID_PREFIX}${device_name}` >>$RTS2_LOG 2>&1
+					rts2_log_end_msg $? $device_name
 					;;
 			esac
 		fi
@@ -253,9 +271,9 @@ function rts2-reload
 		if [ -f ${RTS2_PID_PREFIX}${service_name} ]; then
 		  	case $system in
 				debian|redhat|slackware|cygwin)
-					log_daemon_msg "Reloading $service_name" "rts2-$service"
-					kill -1 `cat ${RTS2_PID_PREFIX}${service_name}`
-					log_end_msg $?
+					rts2_log_daemon_msg "Reloading $service_name" "rts2-$service"
+					kill -1 `cat ${RTS2_PID_PREFIX}${service_name}` >>$RTS2_LOG 2>&1
+					rts2_log_end_msg $? $service_name
 					;;
 			esac
 		fi
