record failed devices, ignore already running one
git-svn-id: http://svn.code.sf.net/p/rts-2/code/trunk/rts-2@11852 65ab8f4e-f147-0410-b3a9-f14133ecfe55

diff --git a/rts2.initd.in b/rts2.initd.in
--- a/rts2.initd.in
+++ b/rts2.initd.in
@@ -29,6 +29,11 @@
 ulimit -c unlimited
 
 #
+# Devices and services which failed to start/stop properly
+#
+failed=""
+
+#
 # Determine which kind of configuration we're using
 #
 system=unknown
@@ -68,6 +73,21 @@ case $system in
 			echo -n $* "  ."
 		}
 
+		function log_progress_msg
+		{
+			echo -n $* "  ."
+		}
+
+		function log_warning_msg
+		{
+			echo -n $* "  ."
+		}
+
+		function log_failure_msg
+		{
+			echo -n $* "  ."
+		}
+
 		function log_end_msg
 		{
 			if [ $1 == 0 ]; then
@@ -77,6 +97,7 @@ case $system in
 				failedc=`expr $failedc + 1`
 			fi
 		}
+
 		function wait_pid
 		{
 			if [ $2 == 0 ]; then
@@ -85,12 +106,14 @@ case $system in
 					sleep 1
 				done
 			fi
-			rts2_log_end_msg $2 $3
+			rts2_start_log_end_msg $2 $3
 		}
+
 		function daemon
 		{
 			$*
 		}
+
 		function killproc
 		{
 			kill $1
@@ -105,25 +128,45 @@ RTS2_BIN_PREFIX=@prefix@/bin
 RTS2_PID_PREFIX=@PREFIX@/var/run/rts2_
 RTS2_LOG=@PREFIX@/var/log/rts2-debug
 
-function rts2_log_daemon_msg
+rts2_log_daemon_msg()
 {
 	log_daemon_msg $*
 	echo `date +'%Y-%m-%dT%H:%M:%S %Z'` '===<<<<<' $* >>$RTS2_LOG
 }
 
-function rts2_log_end_msg
+rts2_start_log_end_msg()
 {
-	log_end_msg $1
-	if [ $1 == 0 ]; then
+	if [ $1 -eq 0 ]; then
+		log_success_msg "Started RTS2 $2 '$failed'"
 		echo `date +'%Y-%m-%dT%H:%M:%S %Z'` '===>>> ok' $2 >>$RTS2_LOG
+	elif [ $1 -eq 1 ]; then
+		log_warning_msg "RTS2 $2 already running"
+		echo `date +'%Y-%m-%dT%H:%M:%S %Z'` '===>>> already running' $2 >>$RTS2_LOG
 	else
+		log_failure_msg "Cannot start $2"
 		echo `date +'%Y-%m-%dT%H:%M:%S %Z'` '===>>> failed' $2 >>$RTS2_LOG
+		failed="$failed $2"
 	fi
 }
 
-
-function rts2-start
+rts2_stop_log_end_msg()
 {
+	if [ $1 == 0 ]; then
+		log_success_msg "Stoping RTS2 $2"
+		echo `date +'%Y-%m-%dT%H:%M:%S %Z'` '===>>> ok' $2 >>$RTS2_LOG
+	elif [ $1 == 1 ]; then
+		log_warning_msg "RTS2 $2 already stopped"
+		echo `date +'%Y-%m-%dT%H:%M:%S %Z'` '===>>> already stopped' $2 >>$RTS2_LOG
+	else
+		log_failure_msg "Cannot stop $2"
+		echo `date +'%Y-%m-%dT%H:%M:%S %Z'` '===>>> failed' $2 >>$RTS2_LOG
+		failed="$failed $2"
+	fi
+}
+
+rts2_start()
+{
+	rts2_log_daemon_msg "Starting RTS2"
 	grep '^centrald' $CENTRALD_FILE | while read centrald centrald_port centrald_options; do
 		if [ "x${centrald_port}" == "x" ]; then
 			centrald_port=@CENTRALD_PORT@
@@ -132,64 +175,66 @@ function rts2-start
 		fi
 		case $system in
 			debian)
-				rts2_log_daemon_msg "Starting RTS2 centrald daemon on port $centrald_port" "rts2-centrald"
 				start-stop-daemon --start --pidfile ${RTS2_PID_PREFIX}centrald_${centrald_port} --exec $RTS2_BIN_PREFIX/rts2-centrald -- $centrald_options >>$RTS2_LOG 2>&1
-				rts2_log_end_msg $? "rts2-centrald $centrald_options"
+				rts2_start_log_end_msg $? "rts2-centrald $centrald_options" "centrald daemon on port $centrald_port"
 				;;
 			redhat|suse|slackware|cygwin)
-				rts2_log_daemon_msg "Starting RTS2 centrald daemon on port $centrald_port" "rts2-centrald"
 				daemon $RTS2_BIN_PREFIX/rts2-centrald $centrald_options >>$RTS2_LOG 2>&1
-				rts2_log_end_msg $? "rts2-centrald $centrald_options"
+				rts2_start_log_end_msg $? "rts2-centrald $centrald_options" "centrald daemon on port $centrald_port"
 				;;
 		esac
 	done
 	CENTRALD_OPTIONS=`grep '^-' $CENTRALD_FILE 2>/dev/null`
-	cat $DEVICE_CONFIG | sed -e 's/#.*$//' | egrep -v '^\s*$' | while read device type device_name options; do
+	while read device type device_name options; do
 		case $system in
 			debian)
-				rts2_log_daemon_msg "Starting $device_name" "rts2-$device-$type"
 				start-stop-daemon --start --pidfile ${RTS2_PID_PREFIX}${device_name} --exec $RTS2_BIN_PREFIX/rts2-$device-$type -- $options $CENTRALD_OPTIONS -d $device_name >>$RTS2_LOG 2>&1 
-				rts2_log_end_msg $? $device_name
+				rts2_start_log_end_msg $? $device_name "$device_name"
 				;;
 			redhat|suse|slackware|cygwin)
-				rts2_log_daemon_msg "Starting $device_name rts2-$device-$type"
 				daemon $RTS2_BIN_PREFIX/rts2-$device-$type $options $CENTRALD_OPTIONS -d $device_name >>$RTS2_LOG 2>&1
+				rts2_start_log_end_msg $? $device_name "$device_name"
 				wait_pid ${RTS2_PID_PREFIX}${device_name} $? $device_name
 				;;
 		esac
-	done
-	cat $SERVICE_CONFIG | sed -e 's/#.*$//' | egrep -v '^\s*$' | while read service service_name options; do
+	done < <(cat $DEVICE_CONFIG | sed -e 's/#.*$//' | egrep -v '^\s*$')
+	while read service service_name options; do
 		case $system in
 			debian)
-				rts2_log_daemon_msg "Starting $service_name" "rts2-$service"
 				start-stop-daemon --start --pidfile ${RTS2_PID_PREFIX}${service_name} --exec $RTS2_BIN_PREFIX/rts2-$service -- $options $CENTRALD_OPTIONS -d $service_name >>$RTS2_LOG 2>&1
-				rts2_log_end_msg $? $service_name
+				rts2_start_log_end_msg $? $service_name "$service_name"
 				;;
 			redhat|suse|slackware|cygwin)
-				rts2_log_daemon_msg "Starting $service_name rts2-$service"
 				daemon $RTS2_BIN_PREFIX/rts2-$service $options $CENTRALD_OPTIONS -d $service_name >>$RTS2_LOG 2>&1
+				rts2_start_log_end_msg $? $service_name "$service_name"
 				wait_pid ${RTS2_PID_PREFIX}${service_name} $? $service_name
 				;;
 		esac
-	done
+	done < <(cat $SERVICE_CONFIG | sed -e 's/#.*$//' | egrep -v '^\s*$')
+	if [ "x$failed" = "x" ]; then
+		log_daemon_msg "RTS2 start"
+		log_end_msg 0
+	else
+		log_failure_msg "Failed to start $failed"
+		log_daemon_msg "RTS2 start"
+		log_end_msg 1
+	fi
 }
 
-function rts2-stop-devices
+rts2_stop_devices()
 {
 	cat $DEVICE_CONFIG | sed -e 's/#.*$//' | egrep -v '^\s*$' | while read device type device_name options; do
 		case $system in
 			debian)
 				if [ -e ${RTS2_PID_PREFIX}${device_name} ]; then
-					rts2_log_daemon_msg "Stopping $device_name" "rts2-$device-$type"
 					start-stop-daemon --stop --pidfile ${RTS2_PID_PREFIX}${device_name} >>$RTS2_LOG 2>&1
-					rts2_log_end_msg $? $device_name
+					rts2_stop_log_end_msg $? $device_name
 				fi
 				;;
 			redhat|suse|slackware|cygwin)
 				if [ -e ${RTS2_PID_PREFIX}${device_name} ]; then
-					rts2_log_daemon_msg "Stopping $device_name" "rts2-$device-$type"
 					killproc `head -n 1 ${RTS2_PID_PREFIX}${device_name}` >>$RTS2_LOG 2>&1
-					rts2_log_end_msg $? $device_name
+					rts2_stop_log_end_msg $? $device_name
 					rm -f ${RTS2_PID_PREFIX}${device_name}
 				fi
 				;;
@@ -197,55 +242,60 @@ function rts2-stop-devices
 	done
 }
 
-function rts2-stop-services
+rts2_stop_services()
 {
-	cat $SERVICE_CONFIG | sed -e 's/#.*$//' | egrep -v '^\s*$' | while read service service_name options; do
+	while read service service_name options; do
 		case $system in
 			debian)
 				if [ -e ${RTS2_PID_PREFIX}$service_name ]; then
-					rts2_log_daemon_msg "Stopping $service_name" "$service_name"
 					start-stop-daemon --stop --pidfile ${RTS2_PID_PREFIX}${service_name} >>$RTS2_LOG 2>&1
-					rts2_log_end_msg $? $service_name
+					rts2_stop_log_end_msg $? $service_name
 				fi
 				;;
 			redhat|suse|slackware|cygwin)
 				if [ -s ${RTS2_PID_PREFIX}$service_name ]; then
-					rts2_log_daemon_msg "Stopping $service_name" "$service_name"
 					killproc `head -n 1 ${RTS2_PID_PREFIX}$service_name` >>$RTS2_LOG 2>&1
-					rts2_log_end_msg $? $service_name
+					rts2_stop_log_end_msg $? $service_name
 					rm -f ${RTS2_PID_PREFIX}$service_name
 				fi
 				;;
 		esac
-	done
+	done < <(cat $SERVICE_CONFIG | sed -e 's/#.*$//' | egrep -v '^\s*$')
 }
 
-function rts2-stop
+rts2_stop()
 {
-        rts2-stop-services
-	rts2-stop-devices
+	rts2_log_daemon_msg "Stopping RTS2"
+	rts2_stop_services
+	rts2_stop_devices
 	if grep '^centrald' $CENTRALD_FILE 2>&1 > /dev/null; then
 		for cf in ${RTS2_PID_PREFIX}centrald_*; do
 		  	case $system in
 				debian)
-					rts2_log_daemon_msg "Stopping centrald daemon" "rts2-centrald"
 					start-stop-daemon --stop --pidfile $cf >>$RTS2_LOG 2>&1
-					rts2_log_end_msg $? rts2-centrald
+					rts2_stop_log_end_msg $? rts2-centrald
 					;;
 				redhat|suse|slackware|cygwin)
 					if [ -s $cf ]; then
-						rts2_log_daemon_msg "Stopping centrald daemon" "rts2-centrald"
 						killproc `head -n 1 $cf` >>$RTS2_LOG 2>&1
-						rts2_log_end_msg $? rts2-centrald
+						rts2_stop_log_end_msg $? rts2-centrald
 						rm -f $cf
 					fi
 					;;
 			esac
 		done
 	fi
+	if [ -z $failed ]; then
+		log_daemon_msg "RTS2 stopped"
+		log_end_msg 0
+	else
+		log_failure_msg "Failed to stop $failed"
+		log_daemon_msg "RTS2 stopped"
+		log_end_msg 1
+	fi
 }
 
-function rts2-reload
+rts2_reload()
 {
 	if grep '^centrald' $CENTRALD_FILE 2>&1 > /dev/null; then
 		for cf in ${RTS2_PID_PREFIX}centrald_*; do
@@ -254,54 +304,54 @@ function rts2-reload
 				debian|redhat|suse|slackware|cygwin)
 					rts2_log_daemon_msg "Reloading centrald daemon (PID $cf)" "rts2-centrald"
 				  	kill -1 `cat $cf` >>$RTS2_LOG 2>&1
-					rts2_log_end_msg $? rts2-centrald
+					rts2_start_log_end_msg $? rts2-centrald
 					;;
 			esac
 		done
 	fi
-	cat $DEVICE_CONFIG | sed -e 's/#.*$//' | egrep -v '^\s*$' | while read device type device_name options; do
+	while read device type device_name options; do
 		if [ -f ${RTS2_PID_PREFIX}${device_name} ]; then
 		  	case $system in
 				debian|redhat|suse|slackware|cygwin)
 					rts2_log_daemon_msg "Reloading $device_name" "rts2-$device-$type"
 					kill -1 `cat ${RTS2_PID_PREFIX}${device_name}` >>$RTS2_LOG 2>&1
-					rts2_log_end_msg $? $device_name
+					rts2_start_log_end_msg $? $device_name
 					;;
 			esac
 		fi
-	done
-	cat $SERVICE_CONFIG | sed -e 's/#.*$//' | egrep -v '^\s*$' | while read service service_name options; do
+	done < <(cat $DEVICE_CONFIG | sed -e 's/#.*$//' | egrep -v '^\s*$')
+	while read service service_name options; do
 		if [ -f ${RTS2_PID_PREFIX}${service_name} ]; then
 		  	case $system in
 				debian|redhat|suse|slackware|cygwin)
 					rts2_log_daemon_msg "Reloading $service_name" "rts2-$service"
 					kill -1 `cat ${RTS2_PID_PREFIX}${service_name}` >>$RTS2_LOG 2>&1
-					rts2_log_end_msg $? $service_name
+					rts2_start_log_end_msg $? $service_name
 					;;
 			esac
 		fi
-	done
+	done < <(cat $SERVICE_CONFIG | sed -e 's/#.*$//' | egrep -v '^\s*$')
 }
 
 case "$1" in
 	start)
-		rts2-start
+		rts2_start
 		;;
 	stop)
-		rts2-stop
+		rts2_stop
 		;;
 	stop-devices)
-		rts2-stop-devices
+		rts2_stop_devices
 		;;
 	stop-services)
-		rts2-stop-services
+		rts2_stop_services
 		;;
 	restart)
-		rts2-stop
-		rts2-start
+		rts2_stop
+		rts2_start
 		;;
 	reload)
-		rts2-reload
+		rts2_reload
 		;;
 	*)
 		echo "Usage /etc/init.d/rts2 (start|stop|stop-devices|stop-services|restart|reload)"
