added -l option to start on localhost,..

diff --git a/scripts/rts2-start.in b/scripts/rts2-start.in
--- a/scripts/rts2-start.in
+++ b/scripts/rts2-start.in
@@ -9,6 +9,11 @@ RTS2_BIN_PREFIX=@bindir@
 RTS2_PID_PREFIX=@LOCK_PREFIX@
 RTS2_LOG=@LOG_FILE@
 
+localstart=0
+
+function start
+{
+
 if [ "x$1" == "x" ]; then
 	echo "starting everything"
 	name="all"
@@ -25,7 +30,21 @@ if [ "x$name" == "xcentrald" -o "x$name" == "xall" ]; then
 			centrald_options="--local-port $centrald_port $centrald_options"
 		fi
 		echo -n "starting centrald on port $centrald_port .. "
-		$RTS2_BIN_PREFIX/rts2-centrald $centrald_options >>$RTS2_LOG 2>&1
+		if [ $localstart == 0 ]; then
+			$RTS2_BIN_PREFIX/rts2-centrald $centrald_options >>$RTS2_LOG 2>&1
+			started=$?
+			if [ $started == 255 ]; then
+				echo "already running"
+			else
+				[ $started == 0 ] && echo "started" || echo "failed"
+			fi
+			if [ $started != 0 -a "x$name" != "xall" ]; then
+				return 1
+			fi
+		else
+			echo "rts2-centrald $extraargs $centrald_options"
+			$RTS2_BIN_PREFIX/rts2-centrald $extraargs $centrald_options
+		fi
 		started=$?
 		if [ $started == 255 ]; then
 			echo "already running"
@@ -33,11 +52,11 @@ if [ "x$name" == "xcentrald" -o "x$name" == "xall" ]; then
 			[ $started == 0 ] && echo "started" || echo "failed"
 		fi
 		if [ $started != 0 -a "x$name" != "xall" ]; then
-			exit 1
+			return 1
 		fi
 	done < <(grep '^centrald' $CENTRALD_FILE)
 	if [ "x$name" != "xall" ]; then
-		exit $started
+		return $started
 	fi
 fi
 
@@ -46,7 +65,21 @@ CENTRALD_OPTIONS=`grep '^-' $CENTRALD_FILE 2>/dev/null`
 while read device type device_name options; do
 	if [ "x$device_name" == "x$name" -o "x$name" == "xall" ]; then 
 		echo -n "starting device $device_name .. "
-		$RTS2_BIN_PREFIX/rts2-$device-$type -d $device_name $options $CENTRALD_OPTIONS >>$RTS2_LOG 2>&1
+		if [ $localstart == 0 ]; then
+			$RTS2_BIN_PREFIX/rts2-$device-$type -d $device_name $options $CENTRALD_OPTIONS >>$RTS2_LOG 2>&1
+			res=$?
+			if [ $res == 255 ]; then
+				echo "already running"
+			else
+				[ $res == 0 ] && echo "started" || echo "failed"
+			fi
+			if [ "x$name" != "xall" ]; then
+				return $res
+			fi
+		else
+			echo "rts2-$device-$type $extraargs -d $device_name $options $CENTRALD_OPTIONS"
+			$RTS2_BIN_PREFIX/rts2-$device-$type $extraargs -d $device_name $options $CENTRALD_OPTIONS
+		fi
 		res=$?
 		if [ $res == 255 ]; then
 			echo "already running"
@@ -54,7 +87,7 @@ while read device type device_name options; do
 			[ $res == 0 ] && echo "started" || echo "failed"
 		fi
 		if [ "x$name" != "xall" ]; then
-			exit $res
+			return $res
 		fi
 	fi
 done < <(cat $DEVICE_CONFIG | sed -e 's/#.*$//' | egrep -v '^\s*$')
@@ -62,7 +95,21 @@ done < <(cat $DEVICE_CONFIG | sed -e 's/#.*$//' | egrep -v '^\s*$')
 while read service service_name options; do
 	if [ "x$service_name" == "x$name" -o "x$name" == "xall" ]; then
 		echo -n "starting  service $service_name .. "
-		$RTS2_BIN_PREFIX/rts2-$service -d $service_name $options $CENTRALD_OPTIONS >>$RTS2_LOG 2>&1
+		if [ $localstart == 0 ]; then
+			$RTS2_BIN_PREFIX/rts2-$service -d $service_name $options $CENTRALD_OPTIONS >>$RTS2_LOG 2>&1
+			res=$?
+			if [ $res == 255 ]; then
+				echo "already running"
+			else
+				[ $res == 0 ] && echo "started" || echo "failed"
+			fi
+			if [ "x$name" != "xall" ]; then
+				return $res
+			fi
+		else
+			echo "rts2-$service $extraargs -d $service_name $options $CENTRALD_OPTIONS"
+			$RTS2_BIN_PREFIX/rts2-$service $extraargs -d $service_name $options $CENTRALD_OPTIONS
+		fi
 		res=$?
 		if [ $res == 255 ]; then
 			echo "already running"
@@ -70,13 +117,41 @@ while read service service_name options; do
 			[ $res == 0 ] && echo "started" || echo "failed"
 		fi
 		if [ "x$name" != "xall" ]; then
-			exit $res
+			return $res
 		fi
 	fi
 done < <(cat $SERVICE_CONFIG | sed -e 's/#.*$//' | egrep -v '^\s*$')
 
 if [ "x$name" != "xall" ]; then
-	exit 1
+	return 1
 fi
 
-exit 0
+return 0
+
+}
+
+count=0
+ret=0
+
+for x in $*; do
+	if [ "$x" == "-l" ]; then
+		localstart=1
+	else
+		count=1
+		start $x
+		r=$?
+		if [ $r -ne 0 ]; then
+			ret=$r
+		fi
+	fi
+done
+
+if [ $count -eq 0 ]; then
+	start ""
+	r=$?
+	if [ $r -ne 0 ]; then
+		ret=$r
+	fi
+fi
+
+exit $ret
