fixes,..
git-svn-id: http://svn.code.sf.net/p/rts-2/code/trunk/rts-2@10189 65ab8f4e-f147-0410-b3a9-f14133ecfe55

diff --git a/scripts/rts2-f/doauto b/scripts/rts2-f/doauto
--- a/scripts/rts2-f/doauto
+++ b/scripts/rts2-f/doauto
@@ -1,6 +1,6 @@
 #!/usr/bin/tcsh
 # start automatic observing. Uses rts2-seltest to select next target, find and
-# execute its script, and waits until it finished before picking a new target
+# execute its script, and waits until finished before picking a new target
 # Version 13
 # updated 03/11/11 EF: added skyfilt (currently g) and firstnight (run >1 night)
 # updated 04/08/11 EF: added check of No. of dome flats
@@ -27,24 +27,42 @@
 # updated 10/26/11 PK: focusing script is run as target 3 from run_obs
 # updated 10/31/11 EF: new sky flat waits now based on sun elevation
 # updated 10/31/11 EF: made NO tele ref the default, -R now forces tele ref
+# Version 16
 # updated 11/16/11 PK: close telescope while in OFF state
-# Copyright (C) 2010-2011 Emilio Falco (FLWO) & Petr Kubanek (Institute of Physics, Czech Republic)
+# updated 11/16/11 EF: try dawn sky flats if fewer than 5 night flats
+# updated 12/01/11 EF: added loop to ensure slit is open, quit after 15 attempts
+# updated 12/05/11 EF: added domeinit at start
+# updated 12/06/11 EF: added ref tele at the start of night
+# updated 12/07/11 EF: added check of skyflats time of day
+# updated 12/31/11 EF: added SKYFLAT1 and 2 for easier skyflat filter choice
+# Version 17
+# updated 01/15/12 PK: do domeflats if in standby
+# updated 01/15/12 PK: print off message just once
+# Version 18
+# updated 02/24/12 EF: fixed startnight/firstnight for restart
+# updated 02/24/12 EF: fixed tracking after restart
+# Copyright (C) 2010-2012 Emilio Falco (FLWO) & Petr Kubanek (Institute of Physics, Czech Republic)
 
 set rts2dir="/home/observer/RTS2-F"
 set lastoffimage=-1
+echo -1 -1 > $lasttarget
 set tar_id=-2
+set slitfile="/Realtime/lib/slit_status"
 alias run_obs 'source /home/observer/rts2-sys/bin/run_obs'
 alias rts2-logcom 'source /home/observer/RTS2-F/rts2.logcom'
 source /home/observer/rts2-sys/bin/rts2-f-env
 $RTS2/bin/rts2-unabort
+# also nunabort...
+rts2-logcom "RTS2-F: script nabort command revoked."
+/bin/rm -f /home/observer/RTS2-F/.NABORT
 #  check status of RTS2-F
 set rts2status=`ps auxw | grep rts2 | grep XMLRPC`
 #echo ${%rts2status}
 if ( ${%rts2status} == 0 ) then
     rts2-logcom "RTS2-F is not running, starting it now."
     /home/observer/rts2-sys/etc/init.d/rts2 start
-    rts2-logcom "STOP weather sensing for now."
-    /bin/killall rts2-sensor-flwo-weather
+#    rts2-logcom "STOP weather sensing for now."
+#    /bin/killall rts2-sensor-flwo-weather
     set rts2status=`ps auxw | grep rts2 | grep XMLRPC`
 #echo ${%rts2status}
     if ( ${%rts2status} == 0 ) then
@@ -75,13 +93,17 @@ set slit=0
 set covers=0
 # set domes to 0 until dome flats done
 set domes = 0
+# print off message
+set printoff = 1
 # we haven't yet run focusing...
 setenv rts2_focusing_succ 0
 # and we haven't yet change telescope focus
-setenv defoc_current 0
+if ( ! (${?defoc_current}) ) set defoc_current=0
 # set flag to 0 until tele ref done:
 set reftele = 1
 set skipref = 1
+# telescope was not stow at morning
+set morningstow = 1
 # NOTE THESE VARIABLES:
 #  startnight=0 if not starting a new run this night (log with >0 obs exists)
 #  startnight=1 if starting a new run this night (no log, or 0 obs in log)
@@ -168,7 +190,7 @@ if ( -e $runlog ) then
     # there were obs entries in the last log present, NOT new night
 	    set startnight = 0
 	else
-    # there were NO obs entries in the last log present, new night
+	# there were NO obs entries in the last log present, new night
 	    set startnight = 1
 	endif
     endif
@@ -177,25 +199,31 @@ else
     set startnight = 1
     set numobs = 0
 endif
-# welcoming message
-if ($startnight == 1) then
+
+# welcome message
+if ( $startnight == 1 ) then
     rts2-logcom ">>>> START RTS2-F robot observations <<<<"
 else
     rts2-logcom ">>>> CONTINUE RTS2-F robot observations <<<<"
     if ( $ignoreDAY ) then
-	rts2-logcom "---RTS2-F: TESTING, ONLY turn tracking ON." 
-	tele domeoff
+	rts2-logcom "---RTS2-F: TESTING, track ON, dome OFF." 
 	tele trackon
+	tele domeoff
+    else
+# make sure we're tracking, dome on  
+	rts2-logcom "---RTS2-F: OBSERVING, track ON, dome ON."
+	tele trackon
+	tele domeon
     endif
 endif
 
 # run forever, or until CTRL-C or jump to exit
 while (1 != 0)
-    if ( $firstnight == 0 ) then
+    if ( $firstnight == 0 && $startnight == 1 ) then
 	source $rts2dir/rts2.domeflattimeWait
+	rts2-logcom ">>>> CONTINUE RTS2-F robot observations <<<<"
 # set runlog name: current run log 
 	source $rts2dir/rts2.setrunlog
-	set startnight = 1
 	set numobs = 0
 	set dosky1 = 0
 	set dosky2 = 0
@@ -204,28 +232,60 @@ while (1 != 0)
 	rts2-logcom "STOProbot at top of RTS2-F loop."
 	exit
     endif
+    set canopen = 0
     set ms = `$RTS2/bin/rts2-xmlrpcclient --config $XMLRPCCON --master-state on`
-    if ( $? == 0 && $ms == 0 && $ignoreOFF == 0 ) then
-	rts2-logcom "---RTS2-F state: OFF"
+    if ( $? != 0 || ( $ms == 0 && $ignoreOFF == 0 ) ) then
+	if ( $? != 0 ) then
+		rts2-logcom "---RTS2-F state unknown"
+	else
+		set ms = `$RTS2/bin/rts2-xmlrpcclient --config $XMLRPCCON --master-state standby`
+		if  ( $printoff != 0 ) then
+			if ( $ms == 0 ) then
+				rts2-logcom "---RTS2-F state: OFF"
+			else
+				rts2-logcom "---RTS2-F state: STANDBY"
+			endif
+		endif
+	endif
 	set slit = `wc -l /Realtime/lib/slit_status | awk '{print $1}'`
 	if ( $slit == 1 ) then
 	  	if ( $tar_id == -2 ) then
-			rts2-logcom "system is not ON. interrupt script now with ctrl+c if you don't want robot to close dome"
+			rts2-logcom "   Dome slit is open\!"
+			rts2-logcom "   CTRL-C to prevent closing dome slit"
 			set count=15
+			echo -n "Dome will close in $count seconds..."
 			while ( $count > 0 )
-				echo -n "Dome will close in $count seconds\r"
 				sleep 1
 				@ count--
+				echo -n "$count "
 			end
+			echo " "
 		endif
-		rts2-logcom "system is not in ON state and slit is opened, shutting down telescope"
+		rts2-logcom "---RTS2-F state: OFF but slit is open"
+		rts2-logcom "   shutting down telescope"
 		source $rts2dir/rts2.shutall
-		echo "---RTS2-F state: OFF"
 	endif
-	rts2-logcom "   switch to ON to observe (MONrobot or web GUI)"
-	rts2-logcom "   OR CTRL-C to exit the robot."
-	sleep 60
-	continue
+	set ms = `$RTS2/bin/rts2-xmlrpcclient --config $XMLRPCCON --master-state off`
+        if ( $? != 0 || ( $ms == 0 && $ignoreOFF == 0 ) ) then
+		if ( $printoff != 0 ) then
+			rts2-logcom "Switch to ON to observe (MONrobot or web GUI)"
+			rts2-logcom "OR CTRL-C to exit the robot."
+			set printoff = 0
+		endif
+		set d = `date +%H:%M:%S`" MST"
+		printf "WAIT for state change... $d\r"
+		sleep 60
+		continue
+	else
+		set printoff = 1
+	endif
+    else
+    	if ( $? == 0 && ( $ms == 1 || $ignoreOFF == 1 ) ) then
+		set canopen = 1
+		set printoff = 1
+	else
+		rts2-logcom "Cannot open slit, need help\!"
+	endif
     endif
 
 # check the slit status, set slit to 1 if open, 0 if closed:
@@ -245,6 +305,19 @@ while (1 != 0)
 	set state = 3
 	set startnight = 0
     endif
+
+    if ( $canopen == 0 && ( $state == 1 || $state == 2 || $state == 3 || $state == 4 ) ) then
+	if ( $printoff != 0 ) then
+		rts2-logcom "STANDBY mode, will not open slit."
+		rts2-logcom "Switch to ON to observer (MONrobot or web GUI)"
+		rts2-logcom "OR CTRL-C to exit the robot."
+		set printoff = 0
+	endif
+	echo -n "WAIT for state change... " `date +%H:%M:%S`" MST" 
+	sleep 60
+	continue
+    endif
+
     switch ($state)
 # DAY
 	case 0:
@@ -298,10 +371,35 @@ while (1 != 0)
 		    exit
 		endif
 		openslit
-		set slit = 1
+		set slitstatus = `wc -l $slitfile | awk '{print $1}'`
+		if ($slitstatus == 1) then
+		    set slit = 1
+# wait for state change to dusk:
+		    while ($state == 1)
+			if ( -e $rts2abort ) then
+			    rts2-logcom "STOProbot called"
+			    exit
+			endif
+			source $rts2dir/rts2.dusktimeWait
+			set state = 2
+		    end
+		else
+		    set count=0
+		    while ($slitstatus == 0 && $count < 15)
+			@ count++
+			rts2-logcom "PROBLEM: SLIT STILL CLOSED, reattempt, sleep 1 min..."
+			sleep 60
+			openslit
+			set slitstatus = `wc -l $slitfile | awk '{print $1}'`
+		    end
+		    if ($count == 15 && $slitstatus == 0) then
+			rts2-logcom "COULD NOT OPEN SLIT, BAD NETWORK? Quit."
+			exit
+		    endif
+		endif
 	    else
 		rts2-logcom "Twilight - slit is open. CTRL-C exits."
-# wait gracefully for state change:
+# wait for state change to dusk:
 		while ($state == 1)
 		   if ( -e $rts2abort ) then
 		      rts2-logcom "STOProbot called"
@@ -314,18 +412,29 @@ while (1 != 0)
 	    breaksw
 # DUSK
 	case 2:
+	   rts2-logcom "---RTS2-F state: dusk"
 #       check to see if u skyflats have been done already, skip if done:
   	   set skyflog = $rts2dir"/FLATS/skies-"`date +%y%m%d`
 	   if ( -e $skyflog ) then
-		set nlog = `grep -c "next u" $skyflog`
-		if ($nlog >= 10) then
-		   set dosky1 = 1
+#       check time of day, if early, need skyflats
+		set timoday = `ls -lat $skyflog | awk '{print substr($7,1,2)}'`
+		if ($timoday > 12) then
+		    set nlog = `grep -c "next u" $skyflog`
+		    if ($nlog > 4) then
+			rts2-logcom "SKYFLATS: done for today."
+			set dosky1 = 1
+		    else
+			rts2-logcom "SKYFLATS: need more for today."
+			set dosky1 = 0
+		    endif
+		else
+		    rts2-logcom "SKYFLATS: NOT done for today."
+		    set dosky1 = 0
 		endif
 	   endif
 
 #	check time until skyflat time
 	   if ($dosky1 == 0) then
-	      rts2-logcom "---RTS2-F state: dusk"
 	      source $rts2dir/rts2.skyflattime
 	      if ( $TTsky == -1 ) then # too late for flats
 		 set dosky1 = 1
@@ -363,20 +472,22 @@ while (1 != 0)
 	      tele trackon
 	      tele domeon
 	      tele seg 1
+	      tempfocus
 	      rts2-logcom "SKYFLAT: take exposures..."
 	      if ( -e $rts2abort ) then
 		 rts2-logcom "STOProbot called"
 		 exit
 	      endif
-#	try u, $skyfilt ...
-	      source $rts2dir/rts2.skyflats "u"
+#	try SKYFILT1, 2...
+	      set skyfilt = `cat $rts2dir"/FLATS/SKYFILT1"`
+	      source $rts2dir/rts2.skyflats $skyfilt
 	      set skyflatstat = $status
 	      if ( -e $rts2abort ) then
 		 rts2-logcom "STOProbot called"
 		 exit
 	      endif
 #
-	      set skyfilt = `cat $rts2dir"/FLATS/SKYFILT"`
+	      set skyfilt = `cat $rts2dir"/FLATS/SKYFILT2"`
 	      if ($skyflatstat) then
 		 source $rts2dir/rts2.skyflats $skyfilt
 		 set skyflatstat = $status
@@ -385,11 +496,6 @@ while (1 != 0)
 		 rts2-logcom "STOProbot called"
 		 exit
 	      endif
-# skip i sky flats 
-#	      if ($skyflatstat) then
-#		 source $rts2dir/rts2.skyflats "i"
-#		 set skyflatstat = $status
-#	      endif
 	      rts2-logcom "SKYFLAT: done, stow tel..."
 # 		...stow tele at end
 	      tele stow
@@ -420,6 +526,15 @@ while (1 != 0)
 	   breaksw
 # NIGHT
         case 3:
+# reference the tel, if -R flag SET, do this before anything else.
+	   if ($reftele == 0) then
+	      rts2-logcom "Reference telescope."
+	      tele stow
+	      tele ref
+	      set reftele = 1
+	      rts2-logcom "---RTS2-F: reference telescope finished." 
+	   endif
+# check slit status first
 	   if ($slit == 0) then
 	      rts2-logcom "---RTS2-F state: night, slit CLOSED, OPEN it\!"
 	      openslit
@@ -429,9 +544,10 @@ while (1 != 0)
 		 exit 
 	      endif
 	   endif
+
 # check whether first observation, or continuing
 #  startnight is set to 0 when testing (ignoreDAY = 1)
-	   if ( $startnight ) then
+	   if ( $startnight == 1 ) then
 	      rts2-logcom "---RTS2-F: start night observations."
 # reset startnight to 0, as we'll take observations after domes, skies, 
 #                           ref tele and focus.
@@ -441,8 +557,12 @@ while (1 != 0)
 	      source $rts2dir/rts2.covers OPEN
 	      rts2-logcom "---RTS2-F: start night, turn tracking, dome ON, seg 1." 
 	      tele trackon
+# added 12/05/11, init dome:
+	      rts2-logcom "---RTS2-F: init, then ON dome." 
+	      tele domeinit
 	      tele domeon
-	      tele seg 1
+#	      tele seg 1
+	      tempfocus
 	   else
 #             open covers if NOT testing	      
 	      if ( $ignoreDAY ) then
@@ -456,7 +576,11 @@ while (1 != 0)
 		 # start tracking after opening covers
   	         rts2-logcom "---RTS2-F: COVERS OPENED, turn tracking, dome ON" 
 	         tele trackon
+# added 12/05/11, init dome:
+		 rts2-logcom "---RTS2-F: init, then ON dome." 
+		 tele domeinit
 	         tele domeon
+		 tempfocus
 	      endif
 	      if ( $covers == 0 ) then
 		 rts2-logcom "COVERS DID NOT OPEN, QUIT"
@@ -468,23 +592,9 @@ while (1 != 0)
 	   endif
 # reset TTsky, to allow for morning skyflats
 	   setenv TTsky 0
-# run FWHM focus script if needed; put == 0 to run it from here, not from run_obs
-	   if ($rts2_focusing_succ == 110) then
-	      if ( -e $rts2abort ) then
+	   if ( -e $rts2abort ) then
 		 rts2-logcom "STOProbot called"
 		 exit
-	      endif
-	      rts2-logcom "Run FWHM focus script. Abort with nabort."
-# start from a reasonable focus
-	      source $rts2dir/rts2.tempfocus
-# now measure best focus and fwhm
-	      source $rts2dir/rts2.findfwhm
-	   else
-	      if ( -e $rts2abort ) then
-		 rts2-logcom "STOProbot called"
-		 exit
-	      endif
-	      source $rts2dir/rts2.tempfocus
 	   endif
 	   # run_obs $target
 	   run_obs
@@ -494,12 +604,12 @@ while (1 != 0)
 	   breaksw
 # DAWN
         case 4:
-#     check to see if $skyfilt skyflats were done in the evening, skip if done:
-	   set skyfilt=`cat $rts2dir"/FLATS/SKYFILT"`
+#     check to see if SKYFILT1 skyflats were done in the evening, skip if done:
+	   set skyfilt=`cat $rts2dir"/FLATS/SKYFILT1"`
   	   set skyflog=$rts2dir"/FLATS/skies-"`date -d yesterday +%y%m%d`
 	   if ( -e $skyflog ) then
 	      set nlog = `grep -c "next $skyfilt" $skyflog`
-	      if ($nlog >= 10) then
+	      if ($nlog >= 5) then
 		 set dosky2 = 1
 	      endif
 	   endif
@@ -554,7 +664,8 @@ while (1 != 0)
 		tele domeon
 		tele seg 1
 	      endif
-#	try $skyfilt, u...
+#	try SKYFILT2, 1...
+	      set skyfilt=`cat $rts2dir"/FLATS/SKYFILT2"`
 	      source $rts2dir/rts2.skyflats $skyfilt
 	      set skyflatstat = $status
 	      if ( -e $rts2abort ) then
@@ -562,7 +673,8 @@ while (1 != 0)
 		 exit
 	      endif
 	      if ($skyflatstat) then
-		 source $rts2dir/rts2.skyflats "u"
+		 set skyfilt=`cat $rts2dir"/FLATS/SKYFILT1"`
+		 source $rts2dir/rts2.skyflats $skyfilt
 		 set skyflatstat = $status
 	      endif
 	      setenv TTsky 0
@@ -571,14 +683,25 @@ while (1 != 0)
 # stow tele, close covers if skyflats done or too late for them
 	   source $rts2dir/rts2.shutall
 #	   rts2-logcom "PLEASE fill the Dewar now\!"
-	   rts2-logcom ">>>> STOP RTS2-F auto script<<<<"
+# current MST hours, minutes
+	   set HLOC=`/home/observer/RTS2-F/rts2.getMSThm -c -h`
+	   set MLOC=`/home/observer/RTS2-F/rts2.getMSThm -c -m`
+	   echo ">>>> Finishing observations at $HLOC $MLOC <<<<"
+	   rts2-logcom ">>>> STOP RTS2-F robot script <<<<"
 # set firstnight=0 to allow robot to run another night if desired
 	   set firstnight = 0
+	   set startnight = 1
+	   set domes = 0
 	   breaksw
 #	   exit
 	case 5:
-	   rts2-logcom "---RTS2-F unknown state $state, quit."
-	   exit
+	   if ($morningstow == 1) then
+	     rts2-logcom "---RTS2-F morning, stowing telescope, sleeping."
+	     source $rts2dir/rts2.shutall
+	     set morningstow = 0
+           endif
+	   sleep 60
+	   breaksw
 	default:
 	   rts2-logcom "---RTS2-F unknown state $state, quit."
 	   exit
